src/lib/Zikula/Bundle/CoreInstallerBundle/Form/Type/LoginType.php
<?php
/**
 * Copyright Zikula Foundation 2014 - Zikula CoreInstaller bundle.
 *
 * This work is contributed to the Zikula Foundation under one or more
 * Contributor Agreements and licensed to You under the following license:
 *
 * @license GNU/LGPLv3 (or at your option, any later version).
 * @package Zikula
 *
 * Please see the NOTICE file distributed with this source code for further
 * information regarding copyright and licensing.
 */

namespace Zikula\Bundle\CoreInstallerBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Callback;

class LoginType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', 'text', array(
                'label' => __('User Name'),
                'label_attr' => array('class' => 'col-sm-3'),
                'data' => __('admin'),
                'constraints' => array(
                    new NotBlank(),
                )))
            ->add('password', 'password', array(
                'label' => __('Password'),
                'label_attr' => array('class' => 'col-sm-3'),
                'constraints' => array(
                    new NotBlank(),
                )));
    }

    public function getName()
    {
        return 'login';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'constraints' => new Callback(array('callback' => array('Zikula\Bundle\CoreInstallerBundle\Validator\CoreInstallerValidator', 'validateAndLogin'))),
            'csrf_protection' => false,
//                'csrf_field_name' => '_token',
//                // a unique key to help generate the secret token
//                'intention'       => '_zk_bdcreds',
        ));
    }
}

src/lib/Zikula/Bundle/CoreInstallerBundle/Resources/views/Upgrade/ajaxupgrader.html.twig
{% extends '@ZikulaCoreInstaller/theme.html.twig' %}

{% block childjavascripts %}
    <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
    <script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/zikulacoreinstaller/js/ajaxcommon.js') }}"></script>
{% endblock %}
{%  block childstylesheets %}
    <link href="{{ asset('bundles/zikulacoreinstaller/css/ajaxinstaller.css') }}" rel="stylesheet" />
{%  endblock %}

{% block title __('Zikula is upgrading!') %}

{% block content %}

<div>
    <div class="progress">
        <div id="progress-bar" class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            <span class="sr-only">Progress bar</span>
        </div>
    </div>

    <div class="text-center"><a href="#upgrade-fieldset" id="beginupgrade" class="btn btn-lg btn-success">{{ __('Begin Upgrader') }}<br />{{ __('be patient!') }} <i class="fa fa-clock-o"></i></a></div>

    <fieldset id="upgrade-fieldset">
        <legend>{{  __("Upgrading Modules and Helpers") }}</legend>

        <div class="row">
            <ul id="ajaxlist" class="fa-ul text-left">
                {% for stage in stages %}
                <li id="{{ stage.name }}" class="text-muted col-sm-5 col-sm-offset-1 pull-left">
                    <i class="fa-li fa fa-circle-o"></i>
                    <span class="pre">{{ stage.pre }}</span>
                    <span class="during" style="display: none;">{{ stage.during }} </span>
                    <span class="success" style="display: none;">{{ stage.success }}</span>
                    <span class="fail" style="display: none;">{{ stage.fail }}</span>
                </li>
                {% endfor %}
            </ul>
        </div>

    </fieldset>

    <div class="text-center"><a href="{{ url('upgrade', { 'stage': 'complete' }) }}" id="continuebutton" class="btn btn-lg btn-success" style="display:none;">{{ __('Finish') }} <i class="fa fa-angle-double-right"></i></a></div>
</div>
{# create a javascript array of all the stages #}
<script>
    var stages = [
    {% for stage in stages %}
        "{{ stage.name }}",
    {% endfor %}
    ];
</script>
{% endblock %}

src/lib/Zikula/Bundle/CoreInstallerBundle/Resources/views/Upgrade/notupgraded.html.twig
{% extends '@ZikulaCoreInstaller/theme.html.twig' %}

{% block title __('Zikula is not upgraded!') %}

{% block body %}
<div class="container">
    <div id="cell">
        <div id="content">
            <div id="maincontent">
                <h1>{{ __("Zikula Application Framework") }}</h1>
                <h2>{{ __("Zikula Core requires upgrade!") }}</h2>
                <p>
                    {{ __f('You are seeing this message because Zikula requires upgrade. You can upgrade Zikula by clicking
                    on the upgrade button, but before doing so please read the %inst%. Further information can be found in the %docs%.',
                    { '%inst%': '<a href="%url%" onclick="window.open(this.href);return false;">%text%</a>' | replace({'%url%': path('doc', {'name': 'UPGRADE-1.4.0.md'}), '%text%': __('upgrade instructions') }),
                      '%docs%': '<a href="%url%" onclick="window.open(this.href);return false;">%text%</a>' | replace({'%url%': 'http://www.zikula.org', '%text%': __('online documentation') }) } ) | raw }}
                </p>
                <noscript><p class="alert alert-warning">{{ __('You have JavaScript disabled. Please activate it to proceed or use the CLI script instead.') }}</p></noscript>
                <div id="upgradebutton" class="row" style="display:none;">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-4">
                        <a class="btn btn-success btn-lg btn-block" href="{{ path('upgrade', {'stage': 'init' }) }}">
                            <i class="fa fa-thumbs-up fa-3x pull-left"></i> {{ __("Upgrade Zikula!") }}<br />{{ __('To version') }} {{ version }}
                        </a>
                    </div>
                    <div class="col-sm-4"></div>
                </div>
                <br />
                <p class="text-muted">
                    {{ __("Zikula is free software released under the GPL license!") }}<br />
                    {{ __f('For more information, please visit %link%.', { '%link%': '<a href="http://zikula.org/" title="Zikula Homepage">http://zikula.org</a>' }) | raw }}
                </p>
            </div>
        </div>
    </div>
</div>
    <script>
        <!--
        jQuery( document ).ready(function( $ ) {
            $('#upgradebutton').show();
        });
        //-->
    </script>
{% endblock %}